version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ai_safari_postgres
    environment:
      POSTGRES_DB: ai_safari_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/database:/docker-entrypoint-initdb.d
    networks:
      - ai_safari_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ai_safari_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_safari_network

  # AI Safari Backend
  backend:
    build: .
    container_name: ai_safari_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ai_safari_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ai_safari_network
    command: npm run dev

volumes:
  postgres_data:
  redis_data:

networks:
  ai_safari_network:
    driver: bridge

